Updated ECS Subscription system to handle exlusion list
IbexOmega/CrazyCanvas pull request #132
Opened 2020-09-25 10:11 UTC by frozenbanana

Third parameter in subscription registration (after ComponentGroup) is exludedComponents.

2020-09-28 17:04 UTC, TheoBerlin requested changes
The branch needs to merge from master because of the new way of handling component types.

2020-09-28 17:04 UTC, TheoBerlin commented on LambdaEngine/Include/ECS/EntitySubscriber.h
> +		//TArray<std::type_index> ExcludedComponentTypes;
Remove commented code

2020-09-28 17:04 UTC, TheoBerlin commented on LambdaEngine/Source/ECS/EntityRegistry.cpp
> +	bool EntityRegistry::EntityHasAllowedTypes(Entity entity, const TArray<const ComponentType*>& queryTypes, const TArray<const ComponentType*>& excludedComponentsTypes = {}) const
Put the default argument in the header file instead. Also I think the default argument can be kept out, since we never use it (decreases complexity => easier to read). But it's up to you, since it's subjective.

2020-09-28 17:04 UTC, TheoBerlin commented on LambdaEngine/Source/ECS/EntityRegistry.cpp
> +		// Entity with excluded componets are not allowed
```suggestion
		// Entity with excluded components are not allowed
```

2020-09-28 17:04 UTC, TheoBerlin commented on LambdaEngine/Source/ECS/EntitySubscriber.cpp
> +            exclude = false;
The algorithm is good, but as the linter suggests, you can use an std algorithm instead, such as:

```suggestion

            if (std::none_of(excludedComponentTypes.Begin(), excludedComponentTypes.End()
                    (const auto* pExcludedType) { pExcludedType == component.TID; }))
            {
                    componentAccessesFiltered.PushBack(component);
            }
```

And then the `exclude` variable can be removed as well.

2020-09-30 06:55 UTC, frozenbanana reviewed
fixed linting warnings

2020-09-30 07:11 UTC, TheoBerlin requested changes

2020-09-30 07:11 UTC, TheoBerlin commented on LambdaEngine/Source/ECS/EntityRegistry.cpp
> +		for (const ComponentType* excludedType : excludedComponentsTypes)
Prefix pointers with a 'p'

2020-09-30 09:31 UTC, TheoBerlin approved these changes

2020-09-30 09:40 UTC, merged