Teamplayer transparent
IbexOmega/CrazyCanvas pull request #332
Opened 2020-11-02 15:12 UTC by frozenbanana

## Purpose
  Team members are now rendered transparently.

## Changes
 - PlayerRenderer is doing three stages. first render teammates in front culling, then backculling, lastly render enemies without backface culling. This way we can still see the backface of paint when we hit enemies.
 - Every render call players are sorted by distance to the viewer in order to draw transparency correctly. Please have an extra look to see if one can optimize this.

## Context
PBR is not ready yet.

2020-11-03 08:15 UTC, jonathan2222 requested changes
One comment about draw order, but overall good.

2020-11-03 08:15 UTC, jonathan2222 commented on CrazyCanvas/Source/RenderStages/PlayerRenderer.cpp
> +		RenderCull(true, modFrameIndex, ppFirstExecutionStage, beginRenderPassDesc, viewport, scissorRect, m_PipelineStateIDNoCull);
Might want to render the enemies before the team members. This is because the blending might be wrong if an enemy is in front of a team member.

2020-11-05 08:34 UTC, skumbananaaa commented on CrazyCanvas/Include/RenderStages/PlayerRenderer.h
> +		glm::vec3 positon;
Stor på variabler bokstav i struct

2020-11-05 08:34 UTC, skumbananaaa commented on CrazyCanvas/Include/RenderStages/PlayerRenderer.h
> +		float32 distance2ToViewer;
Stor på variabler bokstav i struct

2020-11-05 08:45 UTC, frozenbanana commented on CrazyCanvas/Include/RenderStages/PlayerRenderer.h
> +		glm::vec3 positon;
fixed

2020-11-05 08:46 UTC, frozenbanana commented on CrazyCanvas/Include/RenderStages/PlayerRenderer.h
> +		float32 distance2ToViewer;
fixed

2020-11-05 08:47 UTC, skumbananaaa approved these changes

2020-11-05 09:25 UTC, jonathan2222 approved these changes
👍

2020-11-05 10:09 UTC, merged