Render graph cube map
IbexOmega/CrazyCanvas pull request #39
Opened 2020-09-11 12:27 UTC by norda97

Closes: 
- Cube Map
  - Add texture cube array support
  - Add texturecube support in rendergraph
- Rendergraph Polish
  - Add shader resource recursive folder loading
  - Add Push Constants to RenderGraph

Also fixes:
- Window resizing
- Rendergraph error reporting

2020-09-11 14:11 UTC, jonathan2222 approved these changes
Seems good.

2020-09-11 14:11 UTC, jonathan2222 commented on LambdaEngine/Include/Rendering/Core/API/SBT.h
> +		virtual void
This seems weird.  virtual void should be removed.

2020-09-12 11:37 UTC, merged

2020-09-12 11:37 UTC, TheoBerlin requested changes

2020-09-12 11:37 UTC, TheoBerlin commented on Sandbox/Source/Sandbox.cpp
> +
```suggestion
```

Remove commented code

2020-09-12 11:37 UTC, TheoBerlin commented on LambdaEngine/Source/Resources/ResourceManager.cpp
> +		//Spinlock
What is this comment about? I don't see a spinlock being used.

2020-09-12 11:37 UTC, TheoBerlin commented on LambdaEngine/Source/Resources/ResourceLoader.cpp
> +		TArray<void*> stbi_pixels(textureCount);
Isn't this an array of textures? The naming suggests it's an array of pixels.

2020-09-12 11:37 UTC, TheoBerlin commented on LambdaEngine/Source/Resources/ResourceLoader.cpp
> +		}
```suggestion
		for (void* pTexture : stbi_pixels)
		{
			stbi_image_free(pTexture);
		}
```

If you choose to rename the array (stbi_pixels), don't forget to rename it here as well.

2020-09-12 11:37 UTC, TheoBerlin commented on LambdaEngine/Source/Resources/ResourceLoader.cpp
> +		const uint32 textureCount = count;
Can't the count variable be used? Why should it be copied?

2020-09-12 11:37 UTC, TheoBerlin commented on LambdaEngine/Source/Rendering/RenderGraphParser.cpp
> +		TSet<String> resourceNamesActuallyUsed;
I only see strings being inserted into the set; it's never read from. Remove? Also, use an `unordered_set` unless you want the elements sorted.

2020-09-12 11:37 UTC, TheoBerlin commented on LambdaEngine/Source/Rendering/Core/Vulkan/TextureViewVK.cpp
> +			SAFERELEASE(m_Desc.pTexture);
Does SAFERELEASE need to be within the if-statement? If it's nullptr, nothing will happen.

2020-09-12 11:37 UTC, TheoBerlin commented on LambdaEngine/Include/Rendering/RenderGraphTypes.h
> +			if (pRenderStageDesc->Graphics.Shaders.TaskShaderName.size() > 0)		pipelineStageMask |= FPipelineStageFlags::PIPELINE_STAGE_FLAG_TASK_SHADER;
Consider checking `std::string::empty()` instead of `std::string::size()`.