Timed destruction component
IbexOmega/CrazyCanvas pull request #436
Opened 2020-11-20 10:50 UTC by norda97

## Purpose
- Since Particle emitters has to be attached to an entity to spawn particles there were no way to create an entity and easily destroy it. This new component allows an entiy to be created and destroyed after a certain time. This can be used for multiple purposes, but I needed it for the spawning of emitters.

## Changes
 - Added a DestructionComponent and DestructionSystem

## Testing
How have one tested the feature to ensure it works?
- [ ] Tested in Sandbox
- [ ] Tested in Multiplayer with 2 clients
- [ ] Tested in Multiplayer with more than 2 clients
- [ ] Tested in Benchmark

## Context (Optional)
Sometimes, the changes in a pull request don’t convey the amount of investigation and effort that went into debugging an issue.

## Screen Captures (Optional)
If change is a user-facing change it is nice to show it of.

2020-11-20 11:16 UTC, norda97 commented on CrazyCanvas/Include/ECS/Systems/Misc/DestructionSystem.cpp
> +			destructionComp.TimeLeft -= deltaTime.AsSeconds();
```suggestion
			destructionComp.TimeLeft -= float(deltaTime.AsSeconds());
```

2020-11-23 07:55 UTC, Ceanze requested changes

2020-11-23 07:55 UTC, Ceanze commented on CrazyCanvas/Include/ECS/Systems/Misc/DestructionSystem.cpp
> +		RegisterSystem(TYPE_NAME(PlayerAnimationSystem), systemReg);
Wrong type name

2020-11-23 08:04 UTC, norda97 commented on CrazyCanvas/Include/ECS/Systems/Misc/DestructionSystem.cpp
> +		RegisterSystem(TYPE_NAME(PlayerAnimationSystem), systemReg);
Fixed

2020-11-23 08:05 UTC, Ceanze commented on CrazyCanvas/engine_config_crazycanvas.json
> +    "CONFIG_OPTION_VOLUME_MASTER": 0.0,
very nice

2020-11-23 08:05 UTC, Ceanze approved these changes

2020-11-23 13:36 UTC, merged