Log file names and line numbers
IbexOmega/CrazyCanvas pull request #456
Opened 2020-11-26 13:38 UTC by TheoBerlin

## Purpose
Instead of manually typing the file name when logging, as in:
`LOG_ERROR("[BufferVK]: Failed to allocate memory");`

File names and line numbers are now automatically printed, so
`LOG_ERROR("Failed to allocate memory");`
prints
`BufferVK.cpp (105): Created Buffer`

This PR also replaces the various debug logs `D_LOG_`... with `LOG_DEBUG`. Also, PhysX error callbacks now include file names and line numbers.

## Changes
The various `LOG` macros now utilize the compile-time variables `__FILE__` and `__LINE__`.

## Testing
How have one tested the feature to ensure it works?
- [ ] Tested in Sandbox
- [ ] Tested in Multiplayer with 2 clients
- [ ] Tested in Multiplayer with more than 2 clients
- [ ] Tested in Benchmark

2020-11-26 14:20 UTC, TheRealChriAnd commented on CrazyCanvas/Source/States/SandboxState.cpp
> +	//	LOG_DEBUG("[LevelObjectCreator]: Created Directional Light");
```suggestion
	//	LOG_DEBUG("Created Directional Light");
```

2020-11-26 14:21 UTC, TheRealChriAnd commented on CrazyCanvas/Source/World/LevelObjectCreator.cpp
> +		LOG_DEBUG("[LevelObjectCreator]: Created Directional Light");
```suggestion
		LOG_DEBUG("[LevelObjectCreator]: Created Directional Light");
```
```suggestion
		LOG_DEBUG("Created Directional Light");
```

2020-11-26 14:21 UTC, TheRealChriAnd commented on CrazyCanvas/Source/World/LevelObjectCreator.cpp
> +		LOG_DEBUG("[LevelObjectCreator]: Created Point Light");
```suggestion
		LOG_DEBUG("Created Point Light");
```

2020-11-26 14:22 UTC, TheRealChriAnd commented on LambdaEngine/Source/Application/Win32/Win32Application.cpp
> +			LOG_DEBUG("[Win32Application]: Registered Raw Input devices");
```suggestion
			LOG_DEBUG("Registered Raw Input devices");
```

2020-11-26 14:23 UTC, TheRealChriAnd commented on LambdaEngine/Source/Application/Win32/Win32Application.cpp
> +			LOG_DEBUG("[Win32Application]: Unregistered Raw Input devices");
```suggestion
			LOG_DEBUG("Unregistered Raw Input devices");
```

2020-11-26 14:23 UTC, TheRealChriAnd commented on LambdaEngine/Source/Audio/FMOD/AudioDeviceFMOD.cpp
> +			LOG_DEBUG("[FMOD_DEBUG]: [%s : %u : %s] - \"%s\"", pFile, line, pFunc, pMessage);
```suggestion
			LOG_DEBUG("[%s : %u : %s] - \"%s\"", pFile, line, pFunc, pMessage);
```

2020-11-26 14:25 UTC, TheRealChriAnd commented on LambdaEngine/Source/Audio/FMOD/AudioGeometryFMOD.cpp
> +		LOG_DEBUG("[AudioGeometryFMOD]: Successfully initialized %s!", m_pName);
```suggestion
		LOG_DEBUG("Successfully initialized %s!", m_pName);
```

2020-11-26 14:25 UTC, TheRealChriAnd commented on LambdaEngine/Source/Audio/FMOD/MusicFMOD.cpp
> +			LOG_DEBUG("[MusicFMOD]: Volume could not be set for %s", m_Name.c_str());
```suggestion
			LOG_DEBUG("Volume could not be set for %s", m_Name.c_str());
```

2020-11-26 14:26 UTC, TheRealChriAnd commented on LambdaEngine/Source/Audio/FMOD/MusicFMOD.cpp
> +			LOG_DEBUG("[MusicFMOD]: Pitch could not be set for %s", m_Name.c_str());
```suggestion
			LOG_DEBUG("Pitch could not be set for %s", m_Name.c_str());
```

2020-11-26 14:26 UTC, TheRealChriAnd commented on LambdaEngine/Source/Audio/FMOD/ReverbSphereFMOD.cpp
> +		LOG_DEBUG("[ReverbSphereFMOD]: Successfully initialized %s!", m_pName);
```suggestion
		LOG_DEBUG("Successfully initialized %s!", m_pName);
```

2020-11-26 14:26 UTC, TheRealChriAnd commented on LambdaEngine/Source/Audio/FMOD/SoundInstance2DFMOD.cpp
> +				LOG_DEBUG("[SoundInstance2DFMOD]: Volume could not be set for %s", m_pName);
```suggestion
				LOG_DEBUG("Volume could not be set for %s", m_pName);
```

2020-11-26 14:27 UTC, TheRealChriAnd commented on LambdaEngine/Source/Audio/FMOD/SoundInstance2DFMOD.cpp
> +				LOG_DEBUG("[SoundInstance2DFMOD]: Pitch could not be set for %s", m_pName);
```suggestion
				LOG_DEBUG("Pitch could not be set for %s", m_pName);
```

2020-11-26 14:27 UTC, TheRealChriAnd commented on LambdaEngine/Source/Audio/FMOD/SoundInstance3DFMOD.cpp
> +				LOG_DEBUG("[SoundInstance3DFMOD]: 3D Attributes could not be set for %s", m_pName);
```suggestion
				LOG_DEBUG("[SoundInstance3DFMOD]: 3D Attributes could not be set for %s", m_pName);
```
```suggestion
				LOG_DEBUG("3D Attributes could not be set for %s", m_pName);
```

2020-11-26 14:27 UTC, TheRealChriAnd commented on LambdaEngine/Source/Audio/FMOD/SoundInstance3DFMOD.cpp
> +				LOG_DEBUG("[SoundInstance3DFMOD]: Volume could not be set for %s", m_pName);
```suggestion
				LOG_DEBUG("Volume could not be set for %s", m_pName);
```

2020-11-26 14:28 UTC, TheRealChriAnd commented on LambdaEngine/Source/Audio/FMOD/SoundInstance3DFMOD.cpp
> +				LOG_DEBUG("[SoundInstance3DFMOD]: Pitch could not be set for %s", m_pName);
```suggestion
				LOG_DEBUG("Pitch could not be set for %s", m_pName);
```

2020-11-26 14:28 UTC, TheRealChriAnd commented on LambdaEngine/Source/Debug/GPUProfiler.cpp
> +			LOG_DEBUG("[GPUProfiler]: Failed to get available results with %d number of timestamps", timestampCount);
```suggestion
			LOG_DEBUG("Failed to get available results with %d number of timestamps", timestampCount);
```

2020-11-26 14:30 UTC, TheRealChriAnd commented on LambdaEngine/Source/Rendering/Core/Vulkan/CommandQueueVK.cpp
> +			LOG_DEBUG("[CommandQueueVK]: Created commandqueue from queuefamily=%u with index=%u", queueFamilyIndex, index);
```suggestion
			LOG_DEBUG("Created commandqueue from queuefamily=%u with index=%u", queueFamilyIndex, index);
```

2020-11-26 14:30 UTC, TheRealChriAnd commented on LambdaEngine/Source/Rendering/Core/Vulkan/DeviceAllocatorVK.cpp
> +						LOG_DEBUG("[DeviceMemoryPageVK]: Overlap found");
```suggestion
						LOG_DEBUG("Overlap found");
```

2020-11-26 14:31 UTC, TheRealChriAnd commented on LambdaEngine/Source/Rendering/Core/Vulkan/FenceVK.cpp
> +		LOG_DEBUG("[FenceVK]: Created Fence");
```suggestion
		LOG_DEBUG("Created Fence");
```

2020-11-26 14:31 UTC, TheRealChriAnd commented on LambdaEngine/Source/Rendering/Core/Vulkan/FenceVK.cpp
> +				LOG_DEBUG("[FenceVK]: New fence created");
```suggestion
				LOG_DEBUG("New fence created");
```

2020-11-26 14:31 UTC, TheRealChriAnd commented on LambdaEngine/Source/Rendering/Core/Vulkan/FenceVK.cpp
> +				LOG_DEBUG("[FenceVK]: New semaphore created");
```suggestion
				LOG_DEBUG("New semaphore created");
```

2020-11-26 14:32 UTC, TheRealChriAnd commented on LambdaEngine/Source/Rendering/Core/Vulkan/FrameBufferCacheVK.cpp
> +			//LOG_DEBUG("[FrameBufferCacheVK]: Created framebuffer [0]:%p [1]:%p [2]:%p [3]:%p [4]:%p [5]:%p [6]:%p [7]:%p [Depth]:%p [Pass]:%p", key.ColorAttachmentsViews[0], key.ColorAttachmentsViews[1], ke
```suggestion
			//LOG_DEBUG("Created framebuffer [0]:%p [1]:%p [2]:%p [3]:%p [4]:%p [5]:%p [6]:%p [7]:%p [Depth]:%p [Pass]:%p", key.ColorAttachmentsViews[0], key.ColorAttachmentsViews[1], key.ColorAttachmentsViews[2], key.ColorAttachmentsViews[3], key.ColorAttachmentsViews[4], key.ColorAttachmentsViews[5], key.ColorAttachmentsViews[6], key.ColorAttachmentsViews[7], key.DepthStencilView, key.RenderPass);
```

2020-11-26 14:33 UTC, TheRealChriAnd commented on LambdaEngine/Source/Rendering/Core/Vulkan/RayTracingPipelineStateVK.cpp
> +			LOG_DEBUG("[RayTracingPipelineStateVK]: Created Pipeline for %s", pDesc->DebugName.c_str());
```suggestion
			LOG_DEBUG("Created Pipeline for %s", pDesc->DebugName.c_str());
```

2020-11-26 14:33 UTC, TheRealChriAnd commented on LambdaEngine/Source/Rendering/Core/Vulkan/RayTracingPipelineStateVK.cpp
> +			LOG_DEBUG("[RayTracingPipelineStateVK]: Created Pipeline");
```suggestion
			LOG_DEBUG("Created Pipeline");
```

2020-11-26 14:33 UTC, TheRealChriAnd commented on LambdaEngine/Source/Rendering/Core/Vulkan/SBTVK.cpp
> +			LOG_DEBUG("[SBTVK]: Created SBT %s", pDesc->DebugName.c_str());
```suggestion
			LOG_DEBUG("Created SBT %s", pDesc->DebugName.c_str());
```

2020-11-26 14:33 UTC, TheRealChriAnd commented on LambdaEngine/Source/Rendering/Core/Vulkan/SBTVK.cpp
> +			LOG_DEBUG("[SBTVK]: Created SBT");
```suggestion
			LOG_DEBUG("Created SBT");
```

2020-11-26 14:34 UTC, TheRealChriAnd commented on LambdaEngine/Source/Rendering/Core/Vulkan/TextureVK.cpp
> +		LOG_DEBUG("[TextureVK]: Created texture w=%d, h=%d, d=%d", pDesc->Width, pDesc->Height, pDesc->Depth);
```suggestion
		LOG_DEBUG("Created texture w=%d, h=%d, d=%d", pDesc->Width, pDesc->Height, pDesc->Depth);
```

2020-11-26 14:34 UTC, TheRealChriAnd commented on LambdaEngine/Source/Rendering/ParticleCollider.cpp
> +			LOG_DEBUG("[ParticleCollider] Ray query is disabled, disable particle collisions.");
```suggestion
			LOG_DEBUG("Ray query is disabled, disable particle collisions.");
```

2020-11-26 14:34 UTC, TheRealChriAnd commented on LambdaEngine/Source/Rendering/PipelineStateManager.cpp
> +			LOG_DEBUG("[PipelineStateManager]: PipelineState is nullptr");
```suggestion
			LOG_DEBUG("PipelineState is nullptr");
```

2020-11-26 14:35 UTC, TheRealChriAnd commented on LambdaEngine/Source/Rendering/PipelineStateManager.cpp
> +			LOG_DEBUG("[PipelineStateManager]: PipelineState is nullptr");
```suggestion
			LOG_DEBUG("PipelineState is nullptr");
```

2020-11-26 14:35 UTC, TheRealChriAnd commented on LambdaEngine/Source/Rendering/PipelineStateManager.cpp
> +			LOG_DEBUG("[PipelineStateManager]: PipelineState is nullptr");
```suggestion
			LOG_DEBUG("PipelineState is nullptr");
```

2020-11-26 14:35 UTC, TheRealChriAnd requested changes
Looking great, but please fix the duplicated prints

2020-11-27 07:49 UTC, TheoBerlin commented
> Looking great, but please fix the duplicated prints

Done

2020-11-30 08:39 UTC, TheRealChriAnd approved these changes

2020-11-30 08:40 UTC, merged